window.SENTENCES_AUDIO_MAP = {
  "Letter Nn. Sound n. Find the word that starts with Nn.": "assets/audios/sentences/frog_prompt_nn.mp3",
  "Letter Nn. Sound /n/. Find the word that starts with Nn.": "assets/audios/sentences/frog_prompt_nn.mp3",
  "Letter Nn. Find the word that starts with Nn": "assets/audios/sentences/frog_intro_nn.mp3",
  "Letter Bb. Sound b. Find the word that starts with Bb.": "assets/audios/sentences/frog_prompt_bb.mp3",
  "Letter Bb. Sound /b/. Find the word that starts with Bb.": "assets/audios/sentences/frog_prompt_bb.mp3",
  "Letter Bb. Find the word that starts with Bb": "assets/audios/sentences/frog_intro_bb.mp3",
  "Letter Dd. Sound d. Find the word that starts with Dd.": "assets/audios/sentences/frog_prompt_dd.mp3",
  "Letter Dd. Sound /d/. Find the word that starts with Dd.": "assets/audios/sentences/frog_prompt_dd.mp3",
  "Letter Dd. Find the word that starts with Dd": "assets/audios/sentences/frog_intro_dd.mp3",
  "Letter Ff. Sound f. Find the word that starts with Ff.": "assets/audios/sentences/frog_prompt_ff.mp3",
  "Letter Ff. Sound /f/. Find the word that starts with Ff.": "assets/audios/sentences/frog_prompt_ff.mp3",
  "Letter Ff. Find the word that starts with Ff": "assets/audios/sentences/frog_intro_ff.mp3",
  "What is Sue's pet? Sue has a pet. Her cute pet is a little bunny.": "assets/audios/sentences/frog_act_882429c6.mp3",
  "Sue has a pet. Her cute pet is a little bunny. What is Sue's pet?": "assets/audios/sentences/frog_act_882429c6.mp3",
  "Where does the fox hide? The red fox hides quietly inside the cardboard box.": "assets/audios/sentences/frog_act_284468c9.mp3",
  "The red fox hides quietly inside the cardboard box. Where does the fox hide?": "assets/audios/sentences/frog_act_284468c9.mp3",
  "What animal is beside the road? Look at the gentle donkey standing beside the road.": "assets/audios/sentences/frog_act_ff7b83cd.mp3",
  "Look at the gentle donkey standing beside the road. What animal is beside the road?": "assets/audios/sentences/frog_act_ff7b83cd.mp3",
  "What does the animal do? The clever cat likes to drink fresh water.": "assets/audios/sentences/frog_act_2154908d.mp3",
  "The clever cat likes to drink fresh water. What does the animal do?": "assets/audios/sentences/frog_act_2154908d.mp3",
  "What can he do to his dog? He can pat his gentle dog on the head.": "assets/audios/sentences/frog_act_e2a266c9.mp3",
  "He can pat his gentle dog on the head. What can he do to his dog?": "assets/audios/sentences/frog_act_e2a266c9.mp3"
};
